version: '2'

services:
# Database Configuration
   db:
     image: mysql:latest
     volumes:
       - ./db_data/:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: database_1
       MYSQL_USER: user
       MYSQL_PASSWORD: password

# Apache Configuration
   apache:
     image: php:apache
     #build: apache
     volumes:
       - ./web/:/var/www/html
     links:
       - db
     ports:
       - "8080:80"
     privileged: true
